# Generated by Django 5.2.8 on 2025-12-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='eligibility',
            field=models.TextField(blank=True, help_text='Eligibility criteria or prerequisites for enrolling'),
        ),
    ]
