# Generated by Django 5.2.6 on 2025-12-31 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_eligibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('language', 'Language Course'), ('media', 'Media Course'), ('professional', 'Professional Course')], default='professional', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_months',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='course',
            name='eligibility',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
