# Generated by Django 5.2.6 on 2025-12-23 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_course_eligibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('course', 'Course Updates'), ('assignment', 'Assignment & Tests'), ('reminder', 'Reminders & Alerts'), ('community', 'Community Activity'), ('payment', 'Payment Updates'), ('attendance', 'Attendance Updates'), ('system', 'System Messages')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_new_course', models.BooleanField(default=True, help_text='Notify when new course is added')),
                ('notify_course_updates', models.BooleanField(default=True, help_text='Notify about course updates')),
                ('notify_new_assignment', models.BooleanField(default=True)),
                ('notify_assignment_due', models.BooleanField(default=True)),
                ('notify_assignment_graded', models.BooleanField(default=True)),
                ('notify_reminders', models.BooleanField(default=True)),
                ('notify_daily_learning', models.BooleanField(default=True)),
                ('notify_community', models.BooleanField(default=True)),
                ('notify_replies', models.BooleanField(default=True)),
                ('preferred_channels', models.JSONField(blank=True, default=list, help_text='List of preferred delivery channels')),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title_template', models.CharField(help_text='Use {placeholders} for dynamic content', max_length=255)),
                ('message_template', models.TextField(help_text='Use {placeholders} for dynamic content')),
                ('description_template', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='notifications.notificationtype')),
            ],
            options={
                'ordering': ['notification_type', 'name'],
                'unique_together': {('notification_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('description', models.TextField(blank=True, help_text='Additional details')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_object_id', models.IntegerField(blank=True, help_text='ID of related object (assignment, post, etc.)', null=True)),
                ('related_object_type', models.CharField(blank=True, help_text="Type of related object (e.g., 'assignment', 'discussion_post')", max_length=50)),
                ('action_url', models.CharField(blank=True, help_text='URL to navigate to when notification is clicked', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='Send at a specific time', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Notification expires after this date', null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notifications.notificationtype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx'), models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['notification_type', 'created_at'], name='notificatio_notific_5e6e57_idx')],
            },
        ),
    ]
