# Generated by Django 5.2.8 on 2025-12-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_registrationotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('instructor', 'Instructor')], default='student', max_length=20),
        ),
        migrations.DeleteModel(
            name='RegistrationOTP',
        ),
    ]
